# Site settings
title: Shreyansh Sharma
description: 'Software Developer'
url: 'http://ddraig1234.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Shreyansh Sharma'
  email: shreyshrm42010@gmail.com
  twitter_username: shrey sharma
  facebook_username: shreyansh sharma
  github_username:  ddraig1234
  linkedin_username:  shreyansh sharma

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
